"""Hexagonal media ingestion core (ports, use-cases, registry, adapters)."""

from .domain import (
    ClassifiedUrl,
    IngestionOutcome,
    IngestSharedContentCommand,
    IngestSharedContentRequest,
    IngestUrlCommand,
    IngestUrlRequest,
    MediaFamily,
    MediaType,
    ProcessingLifecycleStatus,
    ResolveContext,
    ResolvedMedia,
    SharedContentType,
    SourcePlatform,
    UserContext,
)
from .errors import (
    DEFAULT_INSTAGRAM_PROVIDER_BAD_REQUEST_MESSAGE,
    DEFAULT_INSTAGRAM_PROVIDER_TEMPORARY_MESSAGE,
    DEFAULT_INVALID_URL_MESSAGE,
    DEFAULT_UNSUPPORTED_URL_MESSAGE,
    ClassificationError,
    InvalidUrlError,
    MediaIngestionError,
    NonRetryableProviderResolutionError,
    OrchestrationError,
    ResolutionError,
    ResolverNotFoundError,
    ResolverRegistrationError,
    RetryableProviderResolutionError,
    UnsupportedUrlError,
)
from .ports import ContentResolverPort, SubmissionOrchestratorPort, UrlClassifierPort
from .registry import ResolverRegistry
from .router import ResolverRoute, ResolverRouter
from .use_cases import IngestSharedContentUseCase, IngestUrlUseCase
from .wiring import (
    build_default_ingest_shared_content_use_case,
    build_default_ingest_url_use_case,
    build_default_resolver_registry,
    build_default_resolver_router,
)

__all__ = [
    "ClassifiedUrl",
    "ClassificationError",
    "ContentResolverPort",
    "DEFAULT_INVALID_URL_MESSAGE",
    "DEFAULT_INSTAGRAM_PROVIDER_BAD_REQUEST_MESSAGE",
    "DEFAULT_INSTAGRAM_PROVIDER_TEMPORARY_MESSAGE",
    "DEFAULT_UNSUPPORTED_URL_MESSAGE",
    "IngestionOutcome",
    "IngestSharedContentCommand",
    "IngestSharedContentRequest",
    "IngestSharedContentUseCase",
    "IngestUrlCommand",
    "IngestUrlRequest",
    "IngestUrlUseCase",
    "InvalidUrlError",
    "MediaFamily",
    "MediaIngestionError",
    "MediaType",
    "NonRetryableProviderResolutionError",
    "OrchestrationError",
    "ProcessingLifecycleStatus",
    "RetryableProviderResolutionError",
    "ResolveContext",
    "ResolvedMedia",
    "ResolutionError",
    "ResolverNotFoundError",
    "ResolverRoute",
    "ResolverRouter",
    "ResolverRegistrationError",
    "ResolverRegistry",
    "SharedContentType",
    "SourcePlatform",
    "SubmissionOrchestratorPort",
    "UnsupportedUrlError",
    "UrlClassifierPort",
    "UserContext",
    "build_default_ingest_shared_content_use_case",
    "build_default_ingest_url_use_case",
    "build_default_resolver_registry",
    "build_default_resolver_router",
]
