"""
Lightweight test implementation of Whisper model for integration testing.

This module provides a simplified version of the Whisper model that can be used
in integration tests without requiring the full model to be loaded.
"""
from typing import Dict, Any, Optional


class TestWhisperModel:
    """A lightweight test implementation of the Whisper model."""
    
    def __init__(self, model_name: str = "tiny"):
        """
        Initialize the test Whisper model.
        
        Args:
            model_name: The name of the model to simulate
        """
        self.model_name = model_name
    
    def transcribe(self, audio_path: str, **kwargs) -> Dict[str, Any]:
        """
        Generate a test transcription for the given audio file.
        
        Args:
            audio_path: Path to the audio file
            **kwargs: Additional arguments to pass to the model
            
        Returns:
            A dictionary containing the transcription
            
        Raises:
            RuntimeError: If the audio file cannot be processed
        """
        import os
        
        # Check if the audio file exists and is not empty
        if not os.path.exists(audio_path):
            raise RuntimeError(f"Audio file not found: {audio_path}")
        
        if os.path.getsize(audio_path) == 0:
            raise RuntimeError(f"Audio file is empty: {audio_path}")
        
        # For testing, we return a fixed transcription
        # In a real implementation, we would use the actual Whisper model
        return {
            "text": (
                "This is a test transcription generated by the TestWhisperModel. "
                "It simulates the output of the Whisper model for integration testing. "
                "The transcription discusses artificial intelligence and its impact on society. "
                "AI is transforming various industries including healthcare, finance, and transportation. "
                "Ethical considerations are important when developing AI systems. "
                "Future developments will focus on explainable AI and reducing bias in algorithms."
            ),
            "segments": [
                {
                    "id": 0,
                    "start": 0.0,
                    "end": 5.0,
                    "text": "This is a test transcription generated by the TestWhisperModel."
                },
                {
                    "id": 1,
                    "start": 5.0,
                    "end": 10.0,
                    "text": "It simulates the output of the Whisper model for integration testing."
                },
                {
                    "id": 2,
                    "start": 10.0,
                    "end": 15.0,
                    "text": "The transcription discusses artificial intelligence and its impact on society."
                }
            ],
            "language": "en"
        }


def load_model(model_name: str = "tiny", **kwargs) -> TestWhisperModel:
    """
    Load a test Whisper model.
    
    Args:
        model_name: The name of the model to load
        **kwargs: Additional arguments to pass to the model
        
    Returns:
        A TestWhisperModel instance
    """
    return TestWhisperModel(model_name=model_name)