/**
 * Why `GET /api/artifacts/:id/content` had nothing to hand back.
 *
 * The endpoint answers `409` in two very different situations, and the difference
 * is read off the refusal's `error_code` — never off its message text, which is
 * English prose meant for a log (task-328):
 *
 * - `artifact_not_ready` — the entry is `queued` or `generating`. It resolves on
 *   its own, so coming back to it is legitimate.
 * - `artifact_failed` — the entry is `failed`, which is **terminal**: no worker
 *   will pick it up again, so anything that keeps asking asks forever. The
 *   refusal carries the scope and type a new generation needs, which is what lets
 *   the failure state offer one without a second round-trip.
 */

import type { HttpError } from "./httpError";
import type { ArtifactScope } from "../types/artifacts";
import type { ArtifactType } from "../types/media";

/** What a regeneration has to name. Taken from the refusal, not guessed. */
export interface ArtifactRegenerationTarget {
  scope: ArtifactScope;
  scopeId: string;
  artifactType: ArtifactType;
}

export type ArtifactContentBlock =
  | { kind: "pending" }
  | { kind: "failed"; regeneration: ArtifactRegenerationTarget | null };

/**
 * The types a user may ask for. Not a defensive list: `media_artifacts-dev`
 * holds failed `review_blurb` entries, and that type is generated by the backend
 * only — `POST /api/artifacts` refuses it. An entry of a type absent from here
 * therefore yields no regeneration target, and the failure state shows the
 * failure without offering a button that could only be refused.
 */
const ARTIFACT_TYPES: readonly ArtifactType[] = [
  "summary",
  "summary_short",
  "summary_detailed",
  "notes",
  "quiz",
  "flashcards",
];

function readRegenerationTarget(
  details: Record<string, unknown>,
): ArtifactRegenerationTarget | null {
  const scope = details.scope;
  const scopeId = details.scope_id;
  const artifactType = details.artifact_type;
  if (scope !== "media" && scope !== "folder") return null;
  if (typeof scopeId !== "string" || !scopeId) return null;
  if (
    typeof artifactType !== "string" ||
    !ARTIFACT_TYPES.includes(artifactType as ArtifactType)
  ) {
    return null;
  }
  return {
    scope,
    scopeId,
    artifactType: artifactType as ArtifactType,
  };
}

/**
 * Classify a failed content read, or `null` when the error is something else
 * entirely (a transport failure, a 404, an expired session) and belongs in the
 * screen's generic error state.
 *
 * A `409` this route sends means "no payload to serve"; `artifact_failed` is the
 * only code that makes it terminal, so anything else lands on `pending`.
 */
export function readArtifactContentBlock(
  err: unknown,
): ArtifactContentBlock | null {
  const httpError = err as HttpError | undefined;
  if (httpError?.status !== 409) return null;

  const details = httpError.details ?? {};
  if (httpError.code === "artifact_failed") {
    return { kind: "failed", regeneration: readRegenerationTarget(details) };
  }
  return { kind: "pending" };
}
